### ISSUE TITLE
android issues

### ISSUE THREAD

**Issue by Yelenaa1** [Yelenaa1/android#1]
I want to share an image with anther activity but my code didn't work ,where I missing something?!

``` 
Intent intent = getIntent();
String action = intent.getAction();
String type = intent.getType();
image = findViewById(R.id.imageView_showFromS3);
if (Intent.ACTION_SEND.equals(action) && type == null) {
    if (type.startsWith("image/")) {
        Uri imageUri = (Uri) intent.getParcelableExtra(Intent.EXTRA_STREAM);
        if (imageUri != null) {
            image.setImageURI(imageUri);
            
        }
    }
}
```

**Comment by abrar189** [comment]
hi yelena 

you should change the if statment in type==null to type!=null , and you must set the Visibility for the image

```
 Intent intent = getIntent();
        String action = intent.getAction();
        String type = intent.getType();
        image = findViewById(R.id.imageView_showFromS3);
        if (Intent.ACTION_SEND.equals(action) && type != null) {
            if (type.startsWith("image/")) {
                Uri imageUri = (Uri) intent.getParcelableExtra(Intent.EXTRA_STREAM);
                if (imageUri != null) {
                    image.setImageURI(imageUri);
                    image.setVisibility(View.VISIBLE);
                }
            }
        }
```

**Comment by Yelenaa1** [comment]
> hi yelena
> 
> you should change the if statment in type==null to type!=null , and you must set the Visibility for the image
> 
> ```
>  Intent intent = getIntent();
>         String action = intent.getAction();
>         String type = intent.getType();
>         image = findViewById(R.id.imageView_showFromS3);
>         if (Intent.ACTION_SEND.equals(action) && type != null) {
>             if (type.startsWith("image/")) {
>                 Uri imageUri = (Uri) intent.getParcelableExtra(Intent.EXTRA_STREAM);
>                 if (imageUri != null) {
>                     image.setImageURI(imageUri);
>                     image.setVisibility(View.VISIBLE);
>                 }
>             }
>         }
> ```

thanks abrar its work
